task:
   name: [Multilabel]
   params:
      duration: [2.0, 5.0]
      batch_size: [64]
      per_epoch: [1]
      speech: [True]

data_augmentation:
   name: [AddNoiseFromGaps]
   params:
      snr_min: [10]
      snr_max: [20]
      protocol: [others/corpora_protocol]
      db_yml: [/private/home/dpx/.pyannote/db.yml]
      scheduler: [Linear]
      max_epoch: [100, 300, 500]

feature_extraction:
  name: [LibrosaMelSpectrogram]
  params:
      sample_rate: [16000]
      step: [0.01]
      duration: [0.05]
      n_mels: [128]
      spec_augment: [True]
      frequency_masking_para: [27]
      time_masking_para: [100]
      nb_frequency_masks: [1]
      nb_time_masks: [1]
      scheduler: [data_augmentation/params/scheduler]
      max_epoch: [data_augmentation/params/max_epoch]

architecture:
   name: [ConvRNN]
   params:
      norm: [batch]
      rnn: [LSTM]
      recurrent: [[128, 128],
                  [256, 128],
                  [128, 128, 128, 128],
                  [256, 256, 128, 128]]
      bidirectional: [True]
      linear: [[32, 32],
               [64, 64]]
      kernel_size: [[32],
                    [64],
                    [64, 32],
                    [64, 64],
                    [64, 64, 64, 64],
                    [64, 32, 16, 8]]
      conv_out: [[128],
                 [128, 128],
                 [128, 64],
                 [128, 128, 128, 128],
                 [128, 96, 64, 64]]
      dropout: [0.0, 0.3, 0.5]

scheduler:
   name: [CyclicScheduler]
   params:
      learning_rate: [auto]
      epochs_per_cycle: [14]

preprocessors:
    annotation:
      name: [pyannote.audio.features.GenderChiMapper]

others:
  corpora_protocol: [BabyTrain.SpeakerDiarization.All,
                     CHiME5.SpeakerDiarization.U01,
                     AMI.SpeakerDiarization.MixHeadset]
